FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# api-homework

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/cart]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "cart":{
                    "date": "2015-08-05T08:40:51.620Z",
                    "items": [
                        {
                            "id": 1
                            "toyName": "A"
                            "brandName": "Louis"
                            "gender": "Female"
                            "age": 10
                            "quantity": 2
                            "price": 200
                        },
                        {
                            "id": 2
                            "toyName": "B"
                            "brandName": "Gucci"
                            "gender": "Male"
                            "age": 5
                            "quantity": 1
                            "price": 100
                        }
                    ],
                    "shippingMethod": "Ninja Van"
                    "shippingFee": 155,
                    "totalPrice": 500,
                    "totalFee": 155,
                    "buttonCheckout": "False"
                }
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "cart":{
                "items": [
                    {
                        "1"
                    }
                ]
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /cart/2

    + Body

            {
                "cart":{
                    "date": "2015-08-05T08:40:51.620Z",
                    "items": [
                        {
                            "id": "1"
                            "toyName": "A"
                            "brandName": "Louis"
                            "gender": "Female"
                            "age": 0
                            "quantity": 0
                            "price": 0
                            "isDelete": "False"
                        },
                        {
                            "id": "2"
                            "toyName": "B"
                            "brandName": "Gucci"
                            "gender": "Male"
                            "age": 0
                            "quantity": 0
                            "price": 0
                            "isDelete": "False"
                        }
                    ],
                    "shippingMethod": ""
                    "shippingFee": 0,
                    "totalPrice": 0,
                    "totalFee": 0,
                    "buttonCheckout": "True"
                }
            }